# Generated by Django 3.2.6 on 2022-02-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
